version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Install browsers
      - run:
          name: Install Browsers
          command: |
            sudo apt update
            sudo apt install google-chrome-stable

      - run:
          name: Install Maven Dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: test-report
          destination: test-report

workflows:
  sample:
    jobs:
      - build-and-test
