version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Install latest versions of browsers and their corresponding drivers
      - run:
          name: Install Browsers and WebDriverManager
          command: |
            # Update and install wget if not installed
            sudo apt-get update && sudo apt-get install -y wget

            # Install Firefox (latest version)
            sudo apt-get install -y firefox

            # Install Google Chrome (latest version)
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update && sudo apt-get install -y google-chrome-stable

            # Install WebDriverManager for handling driver binaries
            sudo apt-get install -y maven
            mvn dependency:go-offline
            
            sudo dpkg --configure -a
            sudo apt remove ca-certificates-java
            sudo apt install ca-certificates-java

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: test-report
          destination: test-report

workflows:
  sample:
    jobs:
      - build-and-test