version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -yqq libappindicator1 fonts-liberation
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb
            sudo apt-get install -f
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: test-report
          destination: test-report

workflows:
  sample:
    jobs:
      - build-and-test